dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: Xf12h3bmHUX/1tNeOLS5mQ1I38G4qaLCvn3v1viNqImEx3QbIsuC1jBA8y27u38SWR0XrB8Om2rcoJSOpx0GYlksjshvFvcP15aFTlcHwUfg30otD8daqxPSm8DoGenok0oPxQQMCuEnsArMtA6dmiAnmVaukUorGQ+tnnAKzkeZGiHQTcf8gDpb5efvpxVoqkcRLXgxCMFPGV+k1oLD1RFl1Xg+HbRmHhJ80FwgTeQdIkWxIIGfnDwcIZyEwcfWupMxQZnZH4WcTtaGyIQ39v28f2h7hYNO5XSr4NY+CKNMdXopTjW60vlje98/81iEIJBSfe7fka0ik9uamt/QfavI5E0hZuFCs8l8KYEV32XlCOnB53q5RbAuJXZ8gmoae1WdWBuOcRlqnMbSURAtEiymEv0AiyJ2qgJalrvzIVxoM3ULKIzY74UXn1JSIBryGBy732zPE+HVKs8xVZuePoUHKSMLmu+kC6mpyH5i/OKp1ThosTi9atPbWaFMIDFl6Yva5GyTQgSagliE/Zv6sDZcZiVWwAlwhRfl1Lx3jn+w+NXTgr0l1rn7sNaTmEsT/9kTh6RVO+bAxIcZAxtYhSIrlW7bIUNjhQhThKGCPSW3CnZS6kSAjtStA4Fs0rr/ulAoRaEKQbLrD0SBXAkBA1qEcws2ngKwJ06nTxfVANc=
